using Jellyfin.Plugin.ElCinema.Models;using Jellyfin.Plugin.ElCinema.Services;using MediaBrowser.Controller.Entities.TV;using MediaBrowser.Controller.Providers;using MediaBrowser.Model.Providers;using MediaBrowser.Model.Entities;
namespace Jellyfin.Plugin.ElCinema.Providers;
public sealed class ElCinemaEpisodeProvider(ElCinemaClient client):IRemoteMetadataProvider<Episode,EpisodeInfo>,IHasOrder
{
 public string Name=>Constants.ProviderName;public int Order=>-5;
 public async Task<IEnumerable<RemoteSearchResult>> GetSearchResults(EpisodeInfo i,CancellationToken ct){if(!(Plugin.Instance?.Configuration.EnableEpisodeMetadata??true))return [];var found=await Resolve(i,ct);if(found is null)return [];var r=new RemoteSearchResult{Name=string.IsNullOrWhiteSpace(found.Title)?$"الحلقة {found.EpisodeNumber}":found.Title,Overview=found.Overview,ProductionYear=found.Year,PremiereDate=found.PremiereDate,ImageUrl=found.ImageUrl,SearchProviderName=Name};r.SetProviderId(Constants.ProviderId,ProviderIds.Episode(found.WorkId,found.EpisodeId));return [r];}
 public async Task<MetadataResult<Episode>> GetMetadata(EpisodeInfo i,CancellationToken ct){var r=new MetadataResult<Episode>{Item=new Episode(),ResultLanguage=Constants.Language,Provider=Name};if(!(Plugin.Instance?.Configuration.EnableEpisodeMetadata??true))return r;var ep=await Resolve(i,ct);if(ep is null)return r;r.HasMetadata=true;ProviderMapper.ApplyEpisode(r,r.Item,ep);return r;}
 public Task<HttpResponseMessage> GetImageResponse(string u,CancellationToken ct)=>client.GetImageResponseAsync(u,ct);
 private async Task<ElCinemaEpisode?> Resolve(EpisodeInfo i,CancellationToken ct){var own=i.GetProviderId(Constants.ProviderId);if(ProviderIds.TryEpisode(own,out var wid,out var eid))return await client.GetEpisodeAsync(wid,eid,i.ParentIndexNumber,i.IndexNumber,ct);var work=i.SeriesProviderIds is not null&&i.SeriesProviderIds.TryGetValue(Constants.ProviderId,out var sid)?sid:null;if(string.IsNullOrWhiteSpace(work)||!work.All(char.IsDigit)||!i.IndexNumber.HasValue)return null;var list=await client.GetEpisodesAsync(work,ct);var season=i.ParentIndexNumber??1;var row=list.FirstOrDefault(x=>x.SeasonNumber==season&&x.EpisodeNumber==i.IndexNumber.Value)??list.FirstOrDefault(x=>x.EpisodeNumber==i.IndexNumber.Value);return row is null?null:await client.GetEpisodeAsync(work,row.EpisodeId,row.SeasonNumber,row.EpisodeNumber,ct);}
}
